components:
  schemas:
    Product:
      description: creation of a product
      type: object
      properties:
        id:
          $ref: "#/components/schemas/id"
        name:
          description: nombre del producto
          type: string
          example: corona
        description:
          description: descripcion del producto
          type: string
          example: cerveza suaves 
        imageUrl:
          description: imagen del producto
          type: string
          example: "https://cdn.shopify.com/s/files/1/0366/4442/1770/products/corona_8e2cdd93-e630-493f-a1c0-44a82d488b9e_1200x1200.jpg?v=1593799972"
        brandName:
          description: nombre de la marca
          type: string
          example: corona
        attributes:
          description: atributos del producto
          type: object
          properties:
            style:
              description: tipo de cerveza
              type: string
              example: apa
            ibu: 
              description: nivel de amargor ,un numero mayor signica mas amargor
              type: number
              example: 2 
            abv: 
              description: concetracion alcoholica
              type: number
              example: 1    
        price:
          description: precio del produto
          type: number
          example: 500
        inStock:
          description: si el producto tiene stock o no
          type: boolean
          example: true
        isVisible:
          description: si el producto esta visible
          type: boolean
          example: true
        launchDate:
          description: fecha en la que se creo el producto
          type: date
          example:  2022/03/25
        status:
          $ref: "#/components/schemas/status"

    CreateProduct:
      description: creation of a product
      type: object
      properties:
        name:
          $ref: "#/components/schemas/Product/properties/name"
        description:
          $ref: "#/components/schemas/Product/properties/description"
        imageUrl:
          $ref: "#/components/schemas/Product/properties/imageUrl"
        brandName:
          $ref: "#/components/schemas/Product/properties/brandName"
        attributes:
          description: creation of a product
          type: object
          properties:
            style:
              $ref: "#/components/schemas/Product/properties/attributes/properties/style"
            ibu:
              $ref: "#/components/schemas/Product/properties/attributes/properties/ibu"
            abv:
              $ref: "#/components/schemas/Product/properties/attributes/properties/abv"
          required:
            - style
            - ibu
            - abv
        price:
          $ref: "#/components/schemas/Product/properties/price"
        inStock:
          $ref: "#/components/schemas/Product/properties/inStock"
        isVisible:
          $ref: "#/components/schemas/Product/properties/isVisible"
        launchDate:
          $ref: "#/components/schemas/Product/properties/launchDate"
      required:
        - name
        - imageUrl
        - brandName
        - style
        - ibu
        - abv
        - price
        - inStock

    UpdateProduct:
      description: Update a product
      type: object
      properties:
        name:
          $ref: "#/components/schemas/Product/properties/name"
        description:
          $ref: "#/components/schemas/Product/properties/description"
        imageUrl:
          $ref: "#/components/schemas/Product/properties/imageUrl"
        brandName:
          $ref: "#/components/schemas/Product/properties/brandName"
        attributes:
          description: Update of a product
          type: object
          properties:
            style:
              $ref: "#/components/schemas/Product/properties/attributes/properties/style"
            ibu:
              $ref: "#/components/schemas/Product/properties/attributes/properties/ibu"
            abv:
              $ref: "#/components/schemas/Product/properties/attributes/properties/abv"
      
        price:
          $ref: "#/components/schemas/Product/properties/price"
        inStock:
          $ref: "#/components/schemas/Product/properties/inStock"
        isVisible:
          $ref: "#/components/schemas/Product/properties/isVisible"
        launchDate:
          $ref: "#/components/schemas/Product/properties/launchDate"
     
    FilstersAndOrderBy:
      description: Objeto que sirve para aplicar filtros y ordenar según un criterio.
      type: object
      properties:
        brandName:
          description: El nombre de la marca que utilizamos de filtro
          type: string
          example: corona
        inStock:
          description: Filtrar por los productos que tienen stock o no.
          type: boolean
          example: true
        isVisvile:
          description: Filtrar por los productos visibles o que no estan visibles.
          type: boolean
          example: true
        orderBy:
          description: "Variable que sirve para ordenar segun cuatro criterios \n
           - Mas barato primero\n
           - Menos barato primero\n
           - Mas amargo primero\n
           - Menos amargo primero"
          type: string
          example: moreBitter
